### PR TITLE
Fix emissions table column width

### LINKED ISSUE #461: Ensure that municipality names are not abbreviated on mobile devices
IMG_4201

See Stenung…, should be Stenungstund.

### PR DESCRIPTION
**Pull request by elvbom**
Fix #461 

IMG_1007

### CODE REVIEW

File: components/ComparisonTable.tsx [hunk 1]
```diff
@@ -113,34 +104,22 @@ function ComparisonTable<T extends object>({ data, columns }: TableProps<T>) {
...
+    const lastOrMiddleHeader = index === header.headerGroup.headers.length - 1 ? 'third-header' : 'second-header'
+
+    return (
+      <TableHeader
+        key={header.id}
+        colSpan={header.colSpan}
+        className={header.index > 1 ? 'data-header' : ''}
+        id={index === 0 ? 'first-header' : lastOrMiddleHeader}
+        onClick={header.column.getToggleSortingHandler()}
+        onKeyDown={header.column.getToggleSortingHandler()}
```
Comment (Greenheart) [inline components/ComparisonTable.tsx:121]: Nice! The best way to remove a warning is to fix it :)

**Review by Greenheart — APPROVED** [review]
Nice improvements overall! :+1: I did some padding adjustments to prevent overflow on the smallest screens. This has likely existed before this PR too, but now we solved several things at the same time.
